cmake_minimum_required(VERSION 3.15)
project(pybindcef)

set(CMAKE_CXX_STANDARD 20)

if(DEFINED ENV{CEF_ROOT})
    set(CEF_ROOT $ENV{CEF_ROOT})
else()
    if(WIN32)
        set(CEF_ROOT "$ENV{USERPROFILE}\\Downloads\\cef_binary")
    else()
        set(CEF_ROOT "$ENV{HOME}/Downloads/cef_binary")
    endif()
endif()
file(TO_CMAKE_PATH "${CEF_ROOT}" CEF_ROOT)

if(DEFINED ENV{CEF_DLL_WRAPPER_ROOT})
    set(CEF_DLL_WRAPPER_ROOT $ENV{CEF_DLL_WRAPPER_ROOT})
else()
    if(WIN32)
        set(CEF_DLL_WRAPPER_ROOT "${CEF_ROOT}/build/libcef_dll_wrapper/Release")
    else()
        set(CEF_DLL_WRAPPER_ROOT "${CEF_ROOT}/build/libcef_dll_wrapper")
    endif()
endif()
file(TO_CMAKE_PATH "${CEF_DLL_WRAPPER_ROOT}" CEF_DLL_WRAPPER_ROOT)

message(STATUS "CEF_ROOT: ${CEF_ROOT}")
message(STATUS "CEF_DLL_WRAPPER_ROOT: ${CEF_DLL_WRAPPER_ROOT}")

find_package(Python COMPONENTS Interpreter Development.Module REQUIRED)
set(PYBIND11_FINDPYTHON ON)
find_package(pybind11 REQUIRED)

include_directories(${CEF_ROOT} src/)

set(SOURCES 
    src/bridge.cpp
    src/main_client.cpp
    src/main_app.cpp
    src/handlers/lifespan_handler.cpp
    src/handlers/render_handler.cpp
    src/handlers/download_handler.cpp
    src/handlers/load_handler.cpp
    src/handlers/display_handler.cpp
    src/handlers/context_menu_handler.cpp
    src/handlers/jsdialog_handler.cpp
    src/handlers/find_handler.cpp
    src/handlers/request_handler.cpp
)

if(WIN32)
    message(STATUS "Configuring pybindcef for Windows")
    add_compile_definitions(NOMINMAX)
    list(APPEND SOURCES 
        src/platforms/win/app_win.cpp
        src/platforms/win/gpu_mapper.cpp
    )
elseif(UNIX AND NOT APPLE AND NOT ANDROID)
    message(STATUS "Configuring pybindcef for Linux")
    list(APPEND SOURCES 
        src/platforms/linux/app_linux.cpp
        src/platforms/linux/gpu_mapper.cpp
    )
endif()

pybind11_add_module(_pybindcef ${SOURCES})

if(WIN32)
    target_link_libraries(_pybindcef PRIVATE
        ${CEF_DLL_WRAPPER_ROOT}/libcef_dll_wrapper.lib
        ${CEF_ROOT}/Release/libcef.lib
        d3d11.lib
        opengl32.lib
    )
    set_property(TARGET _pybindcef PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded")
else()
    target_link_libraries(_pybindcef PRIVATE
        ${CEF_DLL_WRAPPER_ROOT}/libcef_dll_wrapper.a
        ${CEF_ROOT}/Release/libcef.so
    )
    set_target_properties(_pybindcef PROPERTIES
        INSTALL_RPATH "$ORIGIN/../pybindcef.libs"
    )
endif()

install(TARGETS _pybindcef DESTINATION .)

if(WIN32)
    if(DEFINED SKBUILD_DATA_DIR)
        set(CEF_DATA_DIR "${SKBUILD_DATA_DIR}/share/pybindcef")
    else()
        set(CEF_DATA_DIR "share/pybindcef")
    endif()
else()
    set(CEF_DATA_DIR "../pybindcef.libs")
endif()

if(WIN32)
    install(DIRECTORY ${CEF_ROOT}/Release/ DESTINATION ${CEF_DATA_DIR} FILES_MATCHING PATTERN "*.dll" PATTERN "*.bin")
    install(DIRECTORY ${CEF_ROOT}/Resources/ DESTINATION ${CEF_DATA_DIR})
else()
    install(DIRECTORY ${CEF_ROOT}/Release/ DESTINATION ${CEF_DATA_DIR} FILES_MATCHING PATTERN "*.so" PATTERN "*.so.*" PATTERN "*.bin")
    install(DIRECTORY ${CEF_ROOT}/Resources/ DESTINATION ${CEF_DATA_DIR})
endif()

add_subdirectory(cef_worker)

